{
  "universe_domain": "googleapis.com",
  "type": "external_account",
  "audience": "${{ secrets.WIP_CONFIG_AUDIENCE }}",
  "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
  "token_url": "https://sts.googleapis.com/v1/token",
  "service_account_impersonation_url": "${{ secrets.WIP_CONFIG_SA_URL }}",
  "credential_source": {
    "file": "sub",
    "format": {
      "type": "text"
    }
  }
}
