name: Deploy Cloud Function
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Authenticate with Google Cloud
      id: 'auth'
      uses: google-github-actions/auth@v3
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        workload_identity_provider: ${{ secrets.WIP_PROVIDER }}
        service-account: ${{ secrets.GCP_SA_EMAIL }}
        scopes: cloud-platform
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ env.GCLOUD_PROJECT }}
    - name: Deploy Cloud Function
      uses: google-github-actions/deploy-cloud-functions@v0.1.0
      with:
        name: generate-user-id
        runtime: python39
        project: ${{ secrets.PROJECT_ID }}
        source: functions/
        entry-point: generate_user_id 
