name: Deploy Cloud Function
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials: ${{ secrets.GCP_SA_KEY }}
        scopes: cloud-platform
    - name: Deploy Cloud Function
      uses: google-github-actions/deploy-cloud-functions@v0.1.0
      with:
        name: generate-user-id
        runtime: python39
        project: ${{ secrets.PROJECT_ID }}
        source: functions/
        entry-point: generate_user_id 
