name: Deploy Cloud Function
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Authenticate with Google Cloud
      id: 'auth'
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIP_PROVIDER }}        
        
    - name: Deploy Cloud Function
      uses: google-github-actions/deploy-cloud-functions@v0.1.0
      with:
        name: generate-user-id
        runtime: python39
        project: ${{ secrets.PROJECT_ID }}
        source: functions/
        entry-point: generate_user_id 
