name: Deploy to Cloud Functions

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checks out your code

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.PROJECT_ID }}   # Replace with your project ID
          service_account_key: ${{ secrets.GCP_SA_KEY }}  # See step 3

      - name: Deploy to Cloud Functions
        run: |
          gcloud functions deploy generate-user-id \
            --runtime python39 \
            --trigger-http \
            --region us-central1 \  
            --source functions \
            --entry-point generate_user_id \
            --allow-unauthenticated \
            --concurrency 100  
